import request from 'supertest'; import express from 'express'; import type { Request, Response, NextFunction } from 'express'; import { createServer } from 'http';
describe('Security - File Upload', () => {
  function uploadApp(){const app=express();const ok=['image/jpeg','image/png','image/webp'];app.post('/u',(req:Request,res:Response)=>{const ct=req.headers['content-type']||'';if(ct.includes('multipart/')){res.json({ok:true});return;}if(!ok.some(t=>ct.includes(t))){res.status(415).json({error:'Unsupported'});return;}res.json({ok:true});});return app;}
  test('accepts jpeg', async () => { expect((await request(createServer(uploadApp())).post('/u').set('Content-Type','image/jpeg').send(Buffer.from([0xff]))).status).toBe(200); });
  test('rejects javascript', async () => { expect((await request(createServer(uploadApp())).post('/u').set('Content-Type','application/javascript').send('x')).status).toBe(415); });
  test('rejects html', async () => { expect((await request(createServer(uploadApp())).post('/u').set('Content-Type','text/html').send('x')).status).toBe(415); });
  test('enforces 10MB limit', async () => { const app=express();app.use((req:Request,res:Response,next:NextFunction)=>{if(parseInt(req.headers['content-length']||'0')>10485760){res.status(413).json({error:'Too large'});return;}next();});app.post('/u',(_r:Request,res:Response)=>res.json({ok:true})); expect((await request(createServer(app)).post('/u').set('Content-Length',String(11*1024*1024))).status).toBe(413); });
  test('path traversal prevention', () => { ['../../../etc/passwd','..\\..\\secret'].forEach(f=>{const s=f.replace(/\.\.\//g,'').replace(/\.\.\\/g,'').replace(/[/\\]/g,'');expect(s).not.toContain('..');expect(s).not.toContain('/');expect(s).not.toContain('\\');}); });
  test('SSRF blocks private IPs', () => { ['http://127.0.0.1/x','http://10.0.0.1/x','http://169.254.169.254/meta'].forEach(u=>{const h=new URL(u).hostname;const p=h.split('.').map(Number) as [number,number,number,number];const priv=['127.0.0.1','localhost','0.0.0.0'].includes(h)||p[0]===10||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===169&&p[1]===254);expect(priv).toBe(true);}); });
});
